// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Notion.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Custom_emojis
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\custom_emojis
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Custom_emojisRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_emojisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/custom_emojis{?name*,page_size*,start_cursor*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_emojisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/custom_emojis{?name*,page_size*,start_cursor*}", rawUrl)
        {
        }
        /// <summary>
        /// List custom emojis
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_409">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_503">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_504">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse?> GetAsCustom_emojisGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse> GetAsCustom_emojisGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Notion.OpenApiClient.Models.Error_api_400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Notion.OpenApiClient.Models.Error_api_401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Notion.OpenApiClient.Models.Error_api_403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Notion.OpenApiClient.Models.Error_api_404.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Notion.OpenApiClient.Models.Error_api_409.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Notion.OpenApiClient.Models.Error_api_429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Notion.OpenApiClient.Models.Error_api_500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Notion.OpenApiClient.Models.Error_api_503.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Notion.OpenApiClient.Models.Error_api_504.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse>(requestInfo, global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List custom emojis
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_409">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_503">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_504">When receiving a 504 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsCustom_emojisGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Notion.OpenApiClient.Models.Error_api_400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Notion.OpenApiClient.Models.Error_api_401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Notion.OpenApiClient.Models.Error_api_403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Notion.OpenApiClient.Models.Error_api_404.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Notion.OpenApiClient.Models.Error_api_409.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Notion.OpenApiClient.Models.Error_api_429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Notion.OpenApiClient.Models.Error_api_500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Notion.OpenApiClient.Models.Error_api_503.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Notion.OpenApiClient.Models.Error_api_504.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisResponse>(requestInfo, global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List custom emojis
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List custom emojis
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Custom_emojisRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_cursor")]
            public string? StartCursor { get; set; }
#nullable restore
#else
            [QueryParameter("start_cursor")]
            public string StartCursor { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Custom_emojisRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisRequestBuilder.Custom_emojisRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
