// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Notion.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Custom_emojis
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Custom_emojisGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether there are more results available.</summary>
        public bool? HasMore { get; set; }
        /// <summary>The cursor to use for the next page of results, or null if there are no more results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor? NextCursor { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor NextCursor { get; set; }
#endif
        /// <summary>Always `list`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Object { get; set; }
#nullable restore
#else
        public string Object { get; set; }
#endif
        /// <summary>The list of custom emojis.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.CustomEmojiResponse>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.CustomEmojiResponse> Results { get; set; }
#endif
        /// <summary>Always `custom_emoji`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "has_more", n => { HasMore = n.GetBoolValue(); } },
                { "next_cursor", n => { NextCursor = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor>(global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetStringValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.CustomEmojiResponse>(global::Soenneker.Notion.OpenApiClient.Models.CustomEmojiResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("has_more", HasMore);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor>("next_cursor", NextCursor);
            writer.WriteStringValue("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.CustomEmojiResponse>("results", Results);
            writer.WriteStringValue("type", Type);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.IdResponse"/>, <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Custom_emojisGetResponse_next_cursor : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1? CustomEmojisGetResponseNextCursorMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1 CustomEmojisGetResponseNextCursorMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.IdResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.IdResponse? IdResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.IdResponse IdResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse.Custom_emojisGetResponse_next_cursor();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomEmojisGetResponseNextCursorMember1 = new global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.IdResponse = new global::Soenneker.Notion.OpenApiClient.Models.IdResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CustomEmojisGetResponseNextCursorMember1 != null)
                {
                    return CustomEmojisGetResponseNextCursorMember1.GetFieldDeserializers();
                }
                else if(IdResponse != null)
                {
                    return IdResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CustomEmojisGetResponseNextCursorMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Custom_emojis.Custom_emojisGetResponse_next_cursorMember1>(null, CustomEmojisGetResponseNextCursorMember1);
                }
                else if(IdResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.IdResponse>(null, IdResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
