// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query
{
    /// <summary>Operator for nested combinator filters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QueryPostRequestBody_filter_filtersMember1_operator
    {
        [EnumMember(Value = "and")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
        [EnumMember(Value = "or")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
    }
}
