// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query
{
    /// <summary>
    /// Optional filter for querying meeting notes. Supports combinator (and/or) and property filters on title, attendees, created_time, created_by, last_edited_time, last_edited_by.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryPostRequestBody_filter : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Nested filters; each may be a combinator (and/or) or property filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters> Filters { get; set; }
#endif
        /// <summary>Operator for combinator filters.</summary>
        public global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_operator? Operator { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter"/> and sets the default values.
        /// </summary>
        public QueryPostRequestBody_filter()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters>(global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters.CreateFromDiscriminatorValue)?.AsList(); } },
                { "operator", n => { Operator = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_operator>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters>("filters", Filters);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_operator>("operator", Operator);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryPostRequestBody_filter_filters : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1? QueryPostRequestBodyFilterFiltersMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1 QueryPostRequestBodyFilterFiltersMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember2? QueryPostRequestBodyFilterFiltersMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember2 QueryPostRequestBodyFilterFiltersMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter.QueryPostRequestBody_filter_filters();
                result.QueryPostRequestBodyFilterFiltersMember1 = new global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1();
                result.QueryPostRequestBodyFilterFiltersMember2 = new global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryPostRequestBodyFilterFiltersMember1 != null || QueryPostRequestBodyFilterFiltersMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryPostRequestBodyFilterFiltersMember1, QueryPostRequestBodyFilterFiltersMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query.QueryPostRequestBody_filter_filtersMember1>(null, QueryPostRequestBodyFilterFiltersMember1, QueryPostRequestBodyFilterFiltersMember2);
            }
        }
    }
}
#pragma warning restore CS0618
