// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Blocks.Meeting_notes.Query
{
    /// <summary>Sort direction. Must be &apos;ascending&apos; or &apos;descending&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QueryPostRequestBody_sort_direction
    {
        [EnumMember(Value = "ascending")]
        #pragma warning disable CS1591
        Ascending,
        #pragma warning restore CS1591
        [EnumMember(Value = "descending")]
        #pragma warning disable CS1591
        Descending,
        #pragma warning restore CS1591
    }
}
