// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Notion.OpenApiClient.Models;
using Soenneker.Notion.OpenApiClient.V1.Data_sources.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Data_sources
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\data_sources
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Data_sourcesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Notion.OpenApiClient.v1.data_sources.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Item.WithData_source_ItemRequestBuilder"/></returns>
        public global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Item.WithData_source_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("data_source_id", position);
                return new global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Item.WithData_source_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Data_sourcesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/data_sources", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Data_sourcesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/data_sources", rawUrl)
        {
        }
        /// <summary>
        /// Create a data source
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_409">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_503">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.Error_api_504">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse?> PostAsync(global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse> PostAsync(global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Notion.OpenApiClient.Models.Error_api_400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Notion.OpenApiClient.Models.Error_api_401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Notion.OpenApiClient.Models.Error_api_403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Notion.OpenApiClient.Models.Error_api_404.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Notion.OpenApiClient.Models.Error_api_409.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Notion.OpenApiClient.Models.Error_api_429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Notion.OpenApiClient.Models.Error_api_500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Notion.OpenApiClient.Models.Error_api_503.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Notion.OpenApiClient.Models.Error_api_504.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse>(requestInfo, global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a data source
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Data_sourcesPostResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse? DataSourceObjectResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse DataSourceObjectResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse? PartialDataSourceObjectResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse PartialDataSourceObjectResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.V1.Data_sources.Data_sourcesRequestBuilder.Data_sourcesPostResponse();
                if("dataSourceObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.DataSourceObjectResponse = new global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse();
                }
                else if("partialDataSourceObjectResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PartialDataSourceObjectResponse = new global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(DataSourceObjectResponse != null)
                {
                    return DataSourceObjectResponse.GetFieldDeserializers();
                }
                else if(PartialDataSourceObjectResponse != null)
                {
                    return PartialDataSourceObjectResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DataSourceObjectResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponse>(null, DataSourceObjectResponse);
                }
                else if(PartialDataSourceObjectResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PartialDataSourceObjectResponse>(null, PartialDataSourceObjectResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
