// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Oauth.Token
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TokenPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bot_id property</summary>
        public Guid? BotId { get; set; }
        /// <summary>The duplicated_template_id property</summary>
        public Guid? DuplicatedTemplateId { get; set; }
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner Owner { get; set; }
#endif
        /// <summary>The refresh_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshToken { get; set; }
#nullable restore
#else
        public string RefreshToken { get; set; }
#endif
        /// <summary>The request_id property</summary>
        public Guid? RequestId { get; set; }
        /// <summary>The token_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenType { get; set; }
#nullable restore
#else
        public string TokenType { get; set; }
#endif
        /// <summary>The workspace_icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceIcon { get; set; }
#nullable restore
#else
        public string WorkspaceIcon { get; set; }
#endif
        /// <summary>The workspace_id property</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>The workspace_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceName { get; set; }
#nullable restore
#else
        public string WorkspaceName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse"/> and sets the default values.
        /// </summary>
        public TokenPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token", n => { AccessToken = n.GetStringValue(); } },
                { "bot_id", n => { BotId = n.GetGuidValue(); } },
                { "duplicated_template_id", n => { DuplicatedTemplateId = n.GetGuidValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner>(global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner.CreateFromDiscriminatorValue); } },
                { "refresh_token", n => { RefreshToken = n.GetStringValue(); } },
                { "request_id", n => { RequestId = n.GetGuidValue(); } },
                { "token_type", n => { TokenType = n.GetStringValue(); } },
                { "workspace_icon", n => { WorkspaceIcon = n.GetStringValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
                { "workspace_name", n => { WorkspaceName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token", AccessToken);
            writer.WriteGuidValue("bot_id", BotId);
            writer.WriteGuidValue("duplicated_template_id", DuplicatedTemplateId);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner>("owner", Owner);
            writer.WriteStringValue("refresh_token", RefreshToken);
            writer.WriteGuidValue("request_id", RequestId);
            writer.WriteStringValue("token_type", TokenType);
            writer.WriteStringValue("workspace_icon", WorkspaceIcon);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteStringValue("workspace_name", WorkspaceName);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TokenPostResponse_owner : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1? TokenPostResponseOwnerMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1 TokenPostResponseOwnerMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember2? TokenPostResponseOwnerMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember2 TokenPostResponseOwnerMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse.TokenPostResponse_owner();
                result.TokenPostResponseOwnerMember1 = new global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1();
                result.TokenPostResponseOwnerMember2 = new global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(TokenPostResponseOwnerMember1 != null || TokenPostResponseOwnerMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TokenPostResponseOwnerMember1, TokenPostResponseOwnerMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Oauth.Token.TokenPostResponse_ownerMember1>(null, TokenPostResponseOwnerMember1, TokenPostResponseOwnerMember2);
            }
        }
    }
}
#pragma warning restore CS0618
