// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Data_sources.Item.Query
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QueryPostResponse_request_status_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "complete")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "incomplete")]
        #pragma warning disable CS1591
        Incomplete,
        #pragma warning restore CS1591
    }
}
