// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPage : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId? BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId? BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId? BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPage();
            result.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId = new global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId();
            result.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId = new global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId();
            result.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId = new global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId != null || BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId != null || BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId, BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId, BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId>(null, BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageCommentId, BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPageDatabaseId, BlockObjectWithSingleLevelOfChildrenRequestLinkToPageLinkToPagePageId);
        }
    }
}
#pragma warning restore CS0618
