// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BlockObjectRequestMember22_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "heading_4")]
        #pragma warning disable CS1591
        Heading_4,
        #pragma warning restore CS1591
    }
}
