// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Which grid lines to show. Pass null to clear.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChartViewConfigRequestGridLines
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal")]
        #pragma warning disable CS1591
        Horizontal,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical")]
        #pragma warning disable CS1591
        Vertical,
        #pragma warning restore CS1591
        [EnumMember(Value = "both")]
        #pragma warning disable CS1591
        Both,
        #pragma warning restore CS1591
    }
}
