// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `comment.created`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CommentCreatedType
    {
        [EnumMember(Value = "comment.created")]
        #pragma warning disable CS1591
        CommentCreated,
        #pragma warning restore CS1591
    }
}
