// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>One of: `audio`, `image`, `pdf`, `productivity`, `video`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CommentObjectResponse_attachments_category
    {
        [EnumMember(Value = "audio")]
        #pragma warning disable CS1591
        Audio,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "pdf")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
        [EnumMember(Value = "productivity")]
        #pragma warning disable CS1591
        Productivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "video")]
        #pragma warning disable CS1591
        Video,
        #pragma warning restore CS1591
    }
}
