// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The parent type. Must be &quot;page_id&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateDatabaseForViewRequestParent_type
    {
        [EnumMember(Value = "page_id")]
        #pragma warning disable CS1591
        PageId,
        #pragma warning restore CS1591
    }
}
