// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `integration`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateACommentRequestDisplayName_type
    {
        [EnumMember(Value = "integration")]
        #pragma warning disable CS1591
        Integration,
        #pragma warning restore CS1591
    }
}
