// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAToken200_ownerMember1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_type? Type { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1"/> and sets the default values.
        /// </summary>
        public CreateAToken200_ownerMember1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_type>(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user>(global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_type>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.PartialUserObjectResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateAToken200_ownerMember1_user : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1? CreateAToken200OwnerMember1UserMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1 CreateAToken200OwnerMember1UserMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PartialUserObjectResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PartialUserObjectResponse? PartialUserObjectResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PartialUserObjectResponse PartialUserObjectResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1.CreateAToken200_ownerMember1_user();
                result.CreateAToken200OwnerMember1UserMember1 = new global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1();
                result.PartialUserObjectResponse = new global::Soenneker.Notion.OpenApiClient.Models.PartialUserObjectResponse();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreateAToken200OwnerMember1UserMember1 != null || PartialUserObjectResponse != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CreateAToken200OwnerMember1UserMember1, PartialUserObjectResponse);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.CreateAToken200_ownerMember1_userMember1>(null, CreateAToken200OwnerMember1UserMember1, PartialUserObjectResponse);
            }
        }
    }
}
#pragma warning restore CS0618
