// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `database.undeleted`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseUndeletedType
    {
        [EnumMember(Value = "database.undeleted")]
        #pragma warning disable CS1591
        DatabaseUndeleted,
        #pragma warning restore CS1591
    }
}
