// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIconMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.PageIconResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataSourceObjectResponseIcon : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIconMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIconMember1? DataSourceObjectResponseIconMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIconMember1 DataSourceObjectResponseIconMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PageIconResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PageIconResponse? PageIconResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PageIconResponse PageIconResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIcon"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIcon CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIcon();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DataSourceObjectResponseIconMember1 != null)
            {
                return DataSourceObjectResponseIconMember1.GetFieldDeserializers();
            }
            else if(PageIconResponse != null)
            {
                return PageIconResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DataSourceObjectResponseIconMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.DataSourceObjectResponseIconMember1>(null, DataSourceObjectResponseIconMember1);
            }
            else if(PageIconResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageIconResponse>(null, PageIconResponse);
            }
        }
    }
}
#pragma warning restore CS0618
