// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `database.schema_updated`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseSchemaUpdatedType
    {
        [EnumMember(Value = "database.schema_updated")]
        #pragma warning disable CS1591
        DatabaseSchemaUpdated,
        #pragma warning restore CS1591
    }
}
