// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `emoji`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmojiPageIconRequest_type
    {
        [EnumMember(Value = "emoji")]
        #pragma warning disable CS1591
        Emoji,
        #pragma warning restore CS1591
    }
}
