// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExistencePropertyFilterAnyOf2_is_not_empty
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "True")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
    }
}
