// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>ISO 8601 timestamp of when the file was imported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImportedTime { get; set; }
#nullable restore
#else
        public string ImportedTime { get; set; }
#endif
        /// <summary>The success property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1Success? Success { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1Success Success { get; set; }
#endif
        /// <summary>Indicates a successful import.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.SuccessType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "imported_time", n => { ImportedTime = n.GetStringValue(); } },
                { "success", n => { Success = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1Success>(global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1Success.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.SuccessType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("imported_time", ImportedTime);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.FileUploadUploadFailedWebhookPayloadAllOf2DataFileImportResultOneOf1Success>("success", Success);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.SuccessType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
