// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The formula result type for grouping.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FormulaDateSubGroupByRequest_type
    {
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
    }
}
