// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// When the schedule stops, when it is bounded.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAgent200ResponseTriggersItemScheduleEnd : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO 8601 timestamp when the schedule stops.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndAt { get; set; }
#nullable restore
#else
        public string EndAt { get; set; }
#endif
        /// <summary>Number of occurrences after which the schedule stops.</summary>
        public int? Occurrences { get; set; }
        /// <summary>Always `date`</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.DateType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.Models.GetAgent200ResponseTriggersItemScheduleEnd"/> and sets the default values.
        /// </summary>
        public GetAgent200ResponseTriggersItemScheduleEnd()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.GetAgent200ResponseTriggersItemScheduleEnd"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.GetAgent200ResponseTriggersItemScheduleEnd CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.GetAgent200ResponseTriggersItemScheduleEnd();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_at", n => { EndAt = n.GetStringValue(); } },
                { "occurrences", n => { Occurrences = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.DateType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("end_at", EndAt);
            writer.WriteIntValue("occurrences", Occurrences);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.DateType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
