// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `icon`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IconPageIconRequest_type
    {
        [EnumMember(Value = "icon")]
        #pragma warning disable CS1591
        Icon,
        #pragma warning restore CS1591
    }
}
