// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `list`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListCustomEmojis200Response_object
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
    }
}
