// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `custom_emoji`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListCustomEmojis200_type
    {
        [EnumMember(Value = "custom_emoji")]
        #pragma warning disable CS1591
        Custom_emoji,
        #pragma warning restore CS1591
    }
}
