// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `comment`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListComments200Response_type
    {
        [EnumMember(Value = "comment")]
        #pragma warning disable CS1591
        Comment,
        #pragma warning restore CS1591
    }
}
