// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `multi_select`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MultiSelectType
    {
        [EnumMember(Value = "multi_select")]
        #pragma warning disable CS1591
        MultiSelect,
        #pragma warning restore CS1591
    }
}
