// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `notion`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NotionType
    {
        [EnumMember(Value = "notion")]
        #pragma warning disable CS1591
        Notion,
        #pragma warning restore CS1591
    }
}
