// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `page.properties_updated`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PagePropertiesUpdatedType
    {
        [EnumMember(Value = "page.properties_updated")]
        #pragma warning disable CS1591
        PagePropertiesUpdated,
        #pragma warning restore CS1591
    }
}
