// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `page.transcription_block.transcript_deleted`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PageTranscriptionBlockTranscriptDeletedType
    {
        [EnumMember(Value = "page.transcription_block.transcript_deleted")]
        #pragma warning disable CS1591
        PageTranscriptionBlockTranscriptDeleted,
        #pragma warning restore CS1591
    }
}
