// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The type of object, always &apos;page_markdown&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PageMarkdownResponse_object
    {
        [EnumMember(Value = "page_markdown")]
        #pragma warning disable CS1591
        Page_markdown,
        #pragma warning restore CS1591
    }
}
