// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `database_id`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParentOfDataSourceRequest_type
    {
        [EnumMember(Value = "database_id")]
        #pragma warning disable CS1591
        DatabaseId,
        #pragma warning restore CS1591
    }
}
