// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchPage_templateMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "template_id")]
        #pragma warning disable CS1591
        Template_id,
        #pragma warning restore CS1591
    }
}
