// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The property type for grouping.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PersonGroupByConfigRequest_type
    {
        [EnumMember(Value = "person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_by")]
        #pragma warning disable CS1591
        Created_by,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_edited_by")]
        #pragma warning disable CS1591
        Last_edited_by,
        #pragma warning restore CS1591
    }
}
