// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostDatabaseQuery : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter Filter { get; set; }
#endif
        /// <summary>The in_trash property</summary>
        public bool? InTrash { get; set; }
        /// <summary>The page_size property</summary>
        public double? PageSize { get; set; }
        /// <summary>Optionally filter the results to only include pages or data sources. Regular, non-wiki databases only support page children. The default behavior is no result type filtering, in other words, returning both pages and data sources for wikis.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_result_type? ResultType { get; set; }
        /// <summary>The sorts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts>? Sorts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts> Sorts { get; set; }
#endif
        /// <summary>The start_cursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartCursor { get; set; }
#nullable restore
#else
        public string StartCursor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter>(global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter.CreateFromDiscriminatorValue); } },
                { "in_trash", n => { InTrash = n.GetBoolValue(); } },
                { "page_size", n => { PageSize = n.GetDoubleValue(); } },
                { "result_type", n => { ResultType = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_result_type>(); } },
                { "sorts", n => { Sorts = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts>(global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_cursor", n => { StartCursor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter>("filter", Filter);
            writer.WriteBoolValue("in_trash", InTrash);
            writer.WriteDoubleValue("page_size", PageSize);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_result_type>("result_type", ResultType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts>("sorts", Sorts);
            writer.WriteStringValue("start_cursor", StartCursor);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.PropertyFilter"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.TimestampFilter"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PostDatabaseQuery_filter : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1? PostDatabaseQueryFilterMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1 PostDatabaseQueryFilterMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PropertyFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PropertyFilter? PropertyFilter { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PropertyFilter PropertyFilter { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.TimestampFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.TimestampFilter? TimestampFilter { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.TimestampFilter TimestampFilter { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_filter();
                result.PostDatabaseQueryFilterMember1 = new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1();
                result.PropertyFilter = new global::Soenneker.Notion.OpenApiClient.Models.PropertyFilter();
                result.TimestampFilter = new global::Soenneker.Notion.OpenApiClient.Models.TimestampFilter();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PostDatabaseQueryFilterMember1 != null || PropertyFilter != null || TimestampFilter != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PostDatabaseQueryFilterMember1, PropertyFilter, TimestampFilter);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_filterMember1>(null, PostDatabaseQueryFilterMember1, PropertyFilter, TimestampFilter);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PostDatabaseQuery_sorts : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1? PostDatabaseQuerySortsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1 PostDatabaseQuerySortsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember2? PostDatabaseQuerySortsMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember2 PostDatabaseQuerySortsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery.PostDatabaseQuery_sorts();
                result.PostDatabaseQuerySortsMember1 = new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1();
                result.PostDatabaseQuerySortsMember2 = new global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PostDatabaseQuerySortsMember1 != null || PostDatabaseQuerySortsMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PostDatabaseQuerySortsMember1, PostDatabaseQuerySortsMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostDatabaseQuery_sortsMember1>(null, PostDatabaseQuerySortsMember1, PostDatabaseQuerySortsMember2);
            }
        }
    }
}
#pragma warning restore CS0618
