// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostPageRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Set to true to receive an async_task response for markdown page creation. Only supported when markdown is provided.</summary>
        public bool? AllowAsync { get; set; }
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>? Children { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest> Children { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest> Content { get; set; }
#endif
        /// <summary>The cover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PageCoverRequest? Cover { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PageCoverRequest Cover { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PageIconRequest? Icon { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PageIconRequest Icon { get; set; }
#endif
        /// <summary>Page content as Markdown, in the syntax set by `markdown_version`: enhanced markdown (`v1`, the default) or Notion-flavored Markdown (`v2`). Mutually exclusive with content/children.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Markdown { get; set; }
#nullable restore
#else
        public string Markdown { get; set; }
#endif
        /// <summary>The Markdown syntax to use. `v1` (the default) is enhanced markdown. `v2` is [Notion-flavored Markdown](/guides/data-apis/notion-flavored-markdown), an opt-in preview.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestMarkdownVersion? MarkdownVersion { get; set; }
        /// <summary>Controls the notifications Notion sends people about this change. Set mode to &quot;silent&quot; to skip page update notifications and @mention notifications, or &quot;default&quot; to use the standard behavior. Database automations, reminders, and connection webhooks still work as usual. Page history, page activity, and workspace audit logs still record the change.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PageWriteNotificationsSchema? Notifications { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PageWriteNotificationsSchema Notifications { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestParent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestParent Parent { get; set; }
#endif
        /// <summary>The position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PagePositionSchema? Position { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PagePositionSchema Position { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestProperties? Properties { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestProperties Properties { get; set; }
#endif
        /// <summary>The template property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestTemplate? Template { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestTemplate Template { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PostPageRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.PostPageRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.PostPageRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_async", n => { AllowAsync = n.GetBoolValue(); } },
                { "children", n => { Children = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>(global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>(global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cover", n => { Cover = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageCoverRequest>(global::Soenneker.Notion.OpenApiClient.Models.PageCoverRequest.CreateFromDiscriminatorValue); } },
                { "icon", n => { Icon = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageIconRequest>(global::Soenneker.Notion.OpenApiClient.Models.PageIconRequest.CreateFromDiscriminatorValue); } },
                { "markdown", n => { Markdown = n.GetStringValue(); } },
                { "markdown_version", n => { MarkdownVersion = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestMarkdownVersion>(); } },
                { "notifications", n => { Notifications = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageWriteNotificationsSchema>(global::Soenneker.Notion.OpenApiClient.Models.PageWriteNotificationsSchema.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestParent>(global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestParent.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PagePositionSchema>(global::Soenneker.Notion.OpenApiClient.Models.PagePositionSchema.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestProperties>(global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestProperties.CreateFromDiscriminatorValue); } },
                { "template", n => { Template = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestTemplate>(global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestTemplate.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_async", AllowAsync);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>("children", Children);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.BlockObjectRequest>("content", Content);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageCoverRequest>("cover", Cover);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageIconRequest>("icon", Icon);
            writer.WriteStringValue("markdown", Markdown);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestMarkdownVersion>("markdown_version", MarkdownVersion);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PageWriteNotificationsSchema>("notifications", Notifications);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestParent>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PagePositionSchema>("position", Position);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestProperties>("properties", Properties);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.PostPageRequestTemplate>("template", Template);
        }
    }
}
#pragma warning restore CS0618
