// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyStatusFilter"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertyFilterVerificationVerification : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter? VerificationPropertyDoesNotEqualFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter VerificationPropertyDoesNotEqualFilter { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyStatusFilter"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyStatusFilter? VerificationPropertyStatusFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyStatusFilter VerificationPropertyStatusFilter { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PropertyFilterVerificationVerification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.PropertyFilterVerificationVerification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Notion.OpenApiClient.Models.PropertyFilterVerificationVerification();
            result.VerificationPropertyDoesNotEqualFilter = new global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter();
            result.VerificationPropertyStatusFilter = new global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyStatusFilter();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(VerificationPropertyDoesNotEqualFilter != null || VerificationPropertyStatusFilter != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(VerificationPropertyDoesNotEqualFilter, VerificationPropertyStatusFilter);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.VerificationPropertyDoesNotEqualFilter>(null, VerificationPropertyDoesNotEqualFilter, VerificationPropertyStatusFilter);
        }
    }
}
#pragma warning restore CS0618
