// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>One of: `requires_action`, `completed`, `failed`, `canceled`, `terminated`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QuerySessionEvents200ResponseResultsItemStatus
    {
        [EnumMember(Value = "requires_action")]
        #pragma warning disable CS1591
        RequiresAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "terminated")]
        #pragma warning disable CS1591
        Terminated,
        #pragma warning restore CS1591
    }
}
