// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryAgents200ResponseResultsItemIconOneOf2 : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The static and animated URLs for the agent avatar.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2CustomAgentAvatar? CustomAgentAvatar { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2CustomAgentAvatar CustomAgentAvatar { get; set; }
#endif
        /// <summary>Type of icon. In this case, a custom agent avatar.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.CustomAgentAvatarType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_agent_avatar", n => { CustomAgentAvatar = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2CustomAgentAvatar>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2CustomAgentAvatar.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.CustomAgentAvatarType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgents200ResponseResultsItemIconOneOf2CustomAgentAvatar>("custom_agent_avatar", CustomAgentAvatar);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.CustomAgentAvatarType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
