// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QuerySessionsRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A session property filter, or an and/or compound filter nested up to two levels deep.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestFilter Filter { get; set; }
#endif
        /// <summary>The number of sessions to return. Maximum: 100.</summary>
        public int? PageSize { get; set; }
        /// <summary>A case-insensitive substring search over session titles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Ordered sort precedence. Defaults to updated_at descending.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestSortsItem>? Sorts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestSortsItem> Sorts { get; set; }
#endif
        /// <summary>The continuation cursor returned by the previous page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartCursor { get; set; }
#nullable restore
#else
        public string StartCursor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestFilter>(global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestFilter.CreateFromDiscriminatorValue); } },
                { "page_size", n => { PageSize = n.GetIntValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "sorts", n => { Sorts = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestSortsItem>(global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestSortsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_cursor", n => { StartCursor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestFilter>("filter", Filter);
            writer.WriteIntValue("page_size", PageSize);
            writer.WriteStringValue("query", Query);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.QuerySessionsRequestSortsItem>("sorts", Sorts);
            writer.WriteStringValue("start_cursor", StartCursor);
        }
    }
}
#pragma warning restore CS0618
