// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Timestamp used to sort agents.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QueryAgentsRequestSortsItemProperty
    {
        [EnumMember(Value = "created_time")]
        #pragma warning disable CS1591
        CreatedTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_run_at")]
        #pragma warning disable CS1591
        LastRunAt,
        #pragma warning restore CS1591
    }
}
