// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checkbox property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemCheckbox? Checkbox { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemCheckbox Checkbox { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemDate? Date { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemDate Date { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemId? Id { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemId Id { get; set; }
#endif
        /// <summary>The mcp_server property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemMcpServer? McpServer { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemMcpServer McpServer { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemNumber? Number { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemNumber Number { get; set; }
#endif
        /// <summary>The people property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemPeople? People { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemPeople People { get; set; }
#endif
        /// <summary>The property property</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.IdProperty? Property { get; set; }
        /// <summary>The select property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemSelect? Select { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemSelect Select { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemStatus? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemStatus Status { get; set; }
#endif
        /// <summary>The string property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemString? String { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemString String { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem"/> and sets the default values.
        /// </summary>
        public QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checkbox", n => { Checkbox = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemCheckbox>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemCheckbox.CreateFromDiscriminatorValue); } },
                { "date", n => { Date = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemDate>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemDate.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemId>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemId.CreateFromDiscriminatorValue); } },
                { "mcp_server", n => { McpServer = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemMcpServer>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemMcpServer.CreateFromDiscriminatorValue); } },
                { "number", n => { Number = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemNumber>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemNumber.CreateFromDiscriminatorValue); } },
                { "people", n => { People = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemPeople>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemPeople.CreateFromDiscriminatorValue); } },
                { "property", n => { Property = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.IdProperty>(); } },
                { "select", n => { Select = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemSelect>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemSelect.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemStatus>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemStatus.CreateFromDiscriminatorValue); } },
                { "string", n => { String = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemString>(global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemString.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemCheckbox>("checkbox", Checkbox);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemDate>("date", Date);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemId>("id", Id);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemMcpServer>("mcp_server", McpServer);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemNumber>("number", Number);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemPeople>("people", People);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.IdProperty>("property", Property);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemSelect>("select", Select);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemStatus>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.QueryAgentsRequestFilterOneOf2OrItemOneOf2OrItemString>("string", String);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
