// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RetrieveSession200Response : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The agent_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgentId { get; set; }
#nullable restore
#else
        public string AgentId { get; set; }
#endif
        /// <summary>The agent_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseAgentVersion? AgentVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseAgentVersion AgentVersion { get; set; }
#endif
        /// <summary>The chat_user_emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseChatUserEmails? ChatUserEmails { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseChatUserEmails ChatUserEmails { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseCreatedBy? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseCreatedBy CreatedBy { get; set; }
#endif
        /// <summary>The credits_used property</summary>
        public double? CreditsUsed { get; set; }
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseError Error { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The message_count property</summary>
        public int? MessageCount { get; set; }
        /// <summary>The models property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseModels? Models { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseModels Models { get; set; }
#endif
        /// <summary>Always `session`</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.SessionObject? Object { get; set; }
        /// <summary>The required_actions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseRequiredActionsItem>? RequiredActions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseRequiredActionsItem> RequiredActions { get; set; }
#endif
        /// <summary>The runs_completed property</summary>
        public int? RunsCompleted { get; set; }
        /// <summary>One of: `queued`, `in_progress`, `requires_action`, `completed`, `failed`, `canceled`, `terminated`</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseStatus? Status { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The tool_call_count property</summary>
        public int? ToolCallCount { get; set; }
        /// <summary>The tool_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseToolTypes? ToolTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseToolTypes ToolTypes { get; set; }
#endif
        /// <summary>The trigger_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerType { get; set; }
#nullable restore
#else
        public string TriggerType { get; set; }
#endif
        /// <summary>The type_labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseTypeLabels? TypeLabels { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseTypeLabels TypeLabels { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent_id", n => { AgentId = n.GetStringValue(); } },
                { "agent_version", n => { AgentVersion = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseAgentVersion>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseAgentVersion.CreateFromDiscriminatorValue); } },
                { "chat_user_emails", n => { ChatUserEmails = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseChatUserEmails>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseChatUserEmails.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseCreatedBy>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseCreatedBy.CreateFromDiscriminatorValue); } },
                { "credits_used", n => { CreditsUsed = n.GetDoubleValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseError>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "message_count", n => { MessageCount = n.GetIntValue(); } },
                { "models", n => { Models = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseModels>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseModels.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.SessionObject>(); } },
                { "required_actions", n => { RequiredActions = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseRequiredActionsItem>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseRequiredActionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "runs_completed", n => { RunsCompleted = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseStatus>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "tool_call_count", n => { ToolCallCount = n.GetIntValue(); } },
                { "tool_types", n => { ToolTypes = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseToolTypes>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseToolTypes.CreateFromDiscriminatorValue); } },
                { "trigger_type", n => { TriggerType = n.GetStringValue(); } },
                { "type_labels", n => { TypeLabels = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseTypeLabels>(global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseTypeLabels.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("agent_id", AgentId);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseAgentVersion>("agent_version", AgentVersion);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseChatUserEmails>("chat_user_emails", ChatUserEmails);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseCreatedBy>("created_by", CreatedBy);
            writer.WriteDoubleValue("credits_used", CreditsUsed);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("message_count", MessageCount);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseModels>("models", Models);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.SessionObject>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseRequiredActionsItem>("required_actions", RequiredActions);
            writer.WriteIntValue("runs_completed", RunsCompleted);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseStatus>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("tool_call_count", ToolCallCount);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseToolTypes>("tool_types", ToolTypes);
            writer.WriteStringValue("trigger_type", TriggerType);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RetrieveSession200ResponseTypeLabels>("type_labels", TypeLabels);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
