// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `rich_text`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RichTextType
    {
        [EnumMember(Value = "rich_text")]
        #pragma warning disable CS1591
        RichText,
        #pragma warning restore CS1591
    }
}
