// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf10"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf2"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf3"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf4"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf5"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf6"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf7"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf8"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RollupSubfilterPropertyFilter : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1? RollupSubfilterPropertyFilterAnyOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1 RollupSubfilterPropertyFilterAnyOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf10? RollupSubfilterPropertyFilterAnyOf10 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf10 RollupSubfilterPropertyFilterAnyOf10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf2? RollupSubfilterPropertyFilterAnyOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf2 RollupSubfilterPropertyFilterAnyOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf3? RollupSubfilterPropertyFilterAnyOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf3 RollupSubfilterPropertyFilterAnyOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf4? RollupSubfilterPropertyFilterAnyOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf4 RollupSubfilterPropertyFilterAnyOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf5? RollupSubfilterPropertyFilterAnyOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf5 RollupSubfilterPropertyFilterAnyOf5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf6? RollupSubfilterPropertyFilterAnyOf6 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf6 RollupSubfilterPropertyFilterAnyOf6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf7? RollupSubfilterPropertyFilterAnyOf7 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf7 RollupSubfilterPropertyFilterAnyOf7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf8? RollupSubfilterPropertyFilterAnyOf8 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf8 RollupSubfilterPropertyFilterAnyOf8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf9? RollupSubfilterPropertyFilterAnyOf9 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf9 RollupSubfilterPropertyFilterAnyOf9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter();
            result.RollupSubfilterPropertyFilterAnyOf1 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1();
            result.RollupSubfilterPropertyFilterAnyOf10 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf10();
            result.RollupSubfilterPropertyFilterAnyOf2 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf2();
            result.RollupSubfilterPropertyFilterAnyOf3 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf3();
            result.RollupSubfilterPropertyFilterAnyOf4 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf4();
            result.RollupSubfilterPropertyFilterAnyOf5 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf5();
            result.RollupSubfilterPropertyFilterAnyOf6 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf6();
            result.RollupSubfilterPropertyFilterAnyOf7 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf7();
            result.RollupSubfilterPropertyFilterAnyOf8 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf8();
            result.RollupSubfilterPropertyFilterAnyOf9 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf9();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RollupSubfilterPropertyFilterAnyOf1 != null || RollupSubfilterPropertyFilterAnyOf10 != null || RollupSubfilterPropertyFilterAnyOf2 != null || RollupSubfilterPropertyFilterAnyOf3 != null || RollupSubfilterPropertyFilterAnyOf4 != null || RollupSubfilterPropertyFilterAnyOf5 != null || RollupSubfilterPropertyFilterAnyOf6 != null || RollupSubfilterPropertyFilterAnyOf7 != null || RollupSubfilterPropertyFilterAnyOf8 != null || RollupSubfilterPropertyFilterAnyOf9 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RollupSubfilterPropertyFilterAnyOf1, RollupSubfilterPropertyFilterAnyOf10, RollupSubfilterPropertyFilterAnyOf2, RollupSubfilterPropertyFilterAnyOf3, RollupSubfilterPropertyFilterAnyOf4, RollupSubfilterPropertyFilterAnyOf5, RollupSubfilterPropertyFilterAnyOf6, RollupSubfilterPropertyFilterAnyOf7, RollupSubfilterPropertyFilterAnyOf8, RollupSubfilterPropertyFilterAnyOf9);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterAnyOf1>(null, RollupSubfilterPropertyFilterAnyOf1, RollupSubfilterPropertyFilterAnyOf10, RollupSubfilterPropertyFilterAnyOf2, RollupSubfilterPropertyFilterAnyOf3, RollupSubfilterPropertyFilterAnyOf4, RollupSubfilterPropertyFilterAnyOf5, RollupSubfilterPropertyFilterAnyOf6, RollupSubfilterPropertyFilterAnyOf7, RollupSubfilterPropertyFilterAnyOf8, RollupSubfilterPropertyFilterAnyOf9);
        }
    }
}
#pragma warning restore CS0618
