// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember10"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember2"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember3"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember4"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember5"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember6"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember7"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember8"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RollupSubfilterPropertyFilter : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1? RollupSubfilterPropertyFilterMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1 RollupSubfilterPropertyFilterMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember10? RollupSubfilterPropertyFilterMember10 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember10 RollupSubfilterPropertyFilterMember10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember2? RollupSubfilterPropertyFilterMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember2 RollupSubfilterPropertyFilterMember2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember3? RollupSubfilterPropertyFilterMember3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember3 RollupSubfilterPropertyFilterMember3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember4? RollupSubfilterPropertyFilterMember4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember4 RollupSubfilterPropertyFilterMember4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember5? RollupSubfilterPropertyFilterMember5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember5 RollupSubfilterPropertyFilterMember5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember6? RollupSubfilterPropertyFilterMember6 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember6 RollupSubfilterPropertyFilterMember6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember7? RollupSubfilterPropertyFilterMember7 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember7 RollupSubfilterPropertyFilterMember7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember8? RollupSubfilterPropertyFilterMember8 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember8 RollupSubfilterPropertyFilterMember8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember9? RollupSubfilterPropertyFilterMember9 { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember9 RollupSubfilterPropertyFilterMember9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilter();
            result.RollupSubfilterPropertyFilterMember1 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1();
            result.RollupSubfilterPropertyFilterMember10 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember10();
            result.RollupSubfilterPropertyFilterMember2 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember2();
            result.RollupSubfilterPropertyFilterMember3 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember3();
            result.RollupSubfilterPropertyFilterMember4 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember4();
            result.RollupSubfilterPropertyFilterMember5 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember5();
            result.RollupSubfilterPropertyFilterMember6 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember6();
            result.RollupSubfilterPropertyFilterMember7 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember7();
            result.RollupSubfilterPropertyFilterMember8 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember8();
            result.RollupSubfilterPropertyFilterMember9 = new global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember9();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RollupSubfilterPropertyFilterMember1 != null || RollupSubfilterPropertyFilterMember10 != null || RollupSubfilterPropertyFilterMember2 != null || RollupSubfilterPropertyFilterMember3 != null || RollupSubfilterPropertyFilterMember4 != null || RollupSubfilterPropertyFilterMember5 != null || RollupSubfilterPropertyFilterMember6 != null || RollupSubfilterPropertyFilterMember7 != null || RollupSubfilterPropertyFilterMember8 != null || RollupSubfilterPropertyFilterMember9 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RollupSubfilterPropertyFilterMember1, RollupSubfilterPropertyFilterMember10, RollupSubfilterPropertyFilterMember2, RollupSubfilterPropertyFilterMember3, RollupSubfilterPropertyFilterMember4, RollupSubfilterPropertyFilterMember5, RollupSubfilterPropertyFilterMember6, RollupSubfilterPropertyFilterMember7, RollupSubfilterPropertyFilterMember8, RollupSubfilterPropertyFilterMember9);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.RollupSubfilterPropertyFilterMember1>(null, RollupSubfilterPropertyFilterMember1, RollupSubfilterPropertyFilterMember10, RollupSubfilterPropertyFilterMember2, RollupSubfilterPropertyFilterMember3, RollupSubfilterPropertyFilterMember4, RollupSubfilterPropertyFilterMember5, RollupSubfilterPropertyFilterMember6, RollupSubfilterPropertyFilterMember7, RollupSubfilterPropertyFilterMember8, RollupSubfilterPropertyFilterMember9);
        }
    }
}
#pragma warning restore CS0618
