// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The property type for grouping.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SelectGroupByConfigRequest_type
    {
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_select")]
        #pragma warning disable CS1591
        Multi_select,
        #pragma warning restore CS1591
    }
}
