// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `session_event`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionEventObject
    {
        [EnumMember(Value = "session_event")]
        #pragma warning disable CS1591
        SessionEvent,
        #pragma warning restore CS1591
    }
}
