// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `session`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SessionObject
    {
        [EnumMember(Value = "session")]
        #pragma warning disable CS1591
        Session,
        #pragma warning restore CS1591
    }
}
