// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StatusPropertyItemObjectResponse_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "property_item")]
        #pragma warning disable CS1591
        PropertyItem,
        #pragma warning restore CS1591
    }
}
