// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TabItemRequestWithSingleLevelOfChildren : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The object property</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_object? Object { get; set; }
        /// <summary>The paragraph property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ParagraphWithSingleLevelOfChildrenRequest? Paragraph { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ParagraphWithSingleLevelOfChildrenRequest Paragraph { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_object>(); } },
                { "paragraph", n => { Paragraph = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ParagraphWithSingleLevelOfChildrenRequest>(global::Soenneker.Notion.OpenApiClient.Models.ParagraphWithSingleLevelOfChildrenRequest.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_object>("object", Object);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ParagraphWithSingleLevelOfChildrenRequest>("paragraph", Paragraph);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.TabItemRequestWithSingleLevelOfChildren_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
