// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Zoom level for the timeline.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimelinePreferenceRequest_zoom_level
    {
        [EnumMember(Value = "hours")]
        #pragma warning disable CS1591
        Hours,
        #pragma warning restore CS1591
        [EnumMember(Value = "day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "week")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
        [EnumMember(Value = "bi_week")]
        #pragma warning disable CS1591
        Bi_week,
        #pragma warning restore CS1591
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "quarter")]
        #pragma warning disable CS1591
        Quarter,
        #pragma warning restore CS1591
        [EnumMember(Value = "year")]
        #pragma warning disable CS1591
        Year,
        #pragma warning restore CS1591
        [EnumMember(Value = "5_years")]
        #pragma warning disable CS1591
        Five_years,
        #pragma warning restore CS1591
    }
}
