// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `unique_id`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UniqueIdType
    {
        [EnumMember(Value = "unique_id")]
        #pragma warning disable CS1591
        UniqueId,
        #pragma warning restore CS1591
    }
}
