// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `unverified`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UnverifiedState
    {
        [EnumMember(Value = "unverified")]
        #pragma warning disable CS1591
        Unverified,
        #pragma warning restore CS1591
    }
}
