// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `replace_content_range`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdatePageMarkdownMember2_type
    {
        [EnumMember(Value = "replace_content_range")]
        #pragma warning disable CS1591
        Replace_content_range,
        #pragma warning restore CS1591
    }
}
