// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>One of: `notion_ai`, `33333333-3333-3333-3333-333333333333`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateSessionRequestAgentIdOneOf2
    {
        [EnumMember(Value = "notion_ai")]
        #pragma warning disable CS1591
        NotionAi,
        #pragma warning restore CS1591
        [EnumMember(Value = "33333333-3333-3333-3333-333333333333")]
        #pragma warning disable CS1591
        Value33333333333333333333333333333333,
        #pragma warning restore CS1591
    }
}
