// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `insert_content`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdatePageMarkdownRequestAllOf1_type
    {
        [EnumMember(Value = "insert_content")]
        #pragma warning disable CS1591
        InsertContent,
        #pragma warning restore CS1591
    }
}
