// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Always `user.message`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserMessageType
    {
        [EnumMember(Value = "user.message")]
        #pragma warning disable CS1591
        UserMessage,
        #pragma warning restore CS1591
    }
}
