// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Date display format (date properties only). &quot;full&quot; = localized full date, &quot;short&quot; = month and day, &quot;month_day_year&quot; = MM/DD/YYYY, &quot;day_month_year&quot; = DD/MM/YYYY, &quot;year_month_day&quot; = YYYY/MM/DD, &quot;relative&quot; = relative dates.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ViewPropertyConfigResponse_date_format
    {
        [EnumMember(Value = "full")]
        #pragma warning disable CS1591
        Full,
        #pragma warning restore CS1591
        [EnumMember(Value = "short")]
        #pragma warning disable CS1591
        Short,
        #pragma warning restore CS1591
        [EnumMember(Value = "month_day_year")]
        #pragma warning disable CS1591
        Month_day_year,
        #pragma warning restore CS1591
        [EnumMember(Value = "day_month_year")]
        #pragma warning disable CS1591
        Day_month_year,
        #pragma warning restore CS1591
        [EnumMember(Value = "year_month_day")]
        #pragma warning disable CS1591
        Year_month_day,
        #pragma warning restore CS1591
        [EnumMember(Value = "relative")]
        #pragma warning disable CS1591
        Relative,
        #pragma warning restore CS1591
    }
}
