// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>
    /// View configuration, typed by view type (table, board, calendar, etc.).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ViewConfigResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether anonymous (non-logged-in) submissions are allowed.</summary>
        public bool? AnonymousSubmissions { get; set; }
        /// <summary>Dependency arrows configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.TimelineArrowsByResponse? ArrowsBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.TimelineArrowsByResponse ArrowsBy { get; set; }
#endif
        /// <summary>Which axis labels to display.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_axis_labels? AxisLabels { get; set; }
        /// <summary>Text caption displayed below the chart. Null when no caption is shown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption? Caption { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption Caption { get; set; }
#endif
        /// <summary>Card layout mode (list shows all properties, compact shows inline).</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_card_layout? CardLayout { get; set; }
        /// <summary>The chart type: column (vertical bars), bar (horizontal bars), line, donut, or number (single value display).</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_chart_type? ChartType { get; set; }
        /// <summary>Whether to color-code items by property.</summary>
        public bool? ColorBy { get; set; }
        /// <summary>Whether chart elements are colored by their numeric value (gradient coloring).</summary>
        public bool? ColorByValue { get; set; }
        /// <summary>Color theme for the chart.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_color_theme? ColorTheme { get; set; }
        /// <summary>Card cover/preview image configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.CoverConfigResponse? Cover { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.CoverConfigResponse Cover { get; set; }
#endif
        /// <summary>Cover image aspect ratio.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_aspect? CoverAspect { get; set; }
        /// <summary>Cover image size.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_size? CoverSize { get; set; }
        /// <summary>Whether to show cumulative values (line charts only).</summary>
        public bool? Cumulative { get; set; }
        /// <summary>Date property used to position items on the calendar - required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatePropertyId { get; set; }
#nullable restore
#else
        public string DatePropertyId { get; set; }
#endif
        /// <summary>Date property name (convenience field).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatePropertyName { get; set; }
#nullable restore
#else
        public string DatePropertyName { get; set; }
#endif
        /// <summary>What to display on donut chart slices.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_donut_labels? DonutLabels { get; set; }
        /// <summary>End date property (optional, for items that span a range).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDatePropertyId { get; set; }
#nullable restore
#else
        public string EndDatePropertyId { get; set; }
#endif
        /// <summary>End date property name (convenience field).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDatePropertyName { get; set; }
#nullable restore
#else
        public string EndDatePropertyName { get; set; }
#endif
        /// <summary>Index of the last frozen column. Columns up to and including this index are frozen.</summary>
        public int? FrozenColumnIndex { get; set; }
        /// <summary>Which grid lines to display.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_grid_lines? GridLines { get; set; }
        /// <summary>Vertical (row) grouping configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse? GroupBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse GroupBy { get; set; }
#endif
        /// <summary>How grouped/stacked bars are displayed. &quot;normal&quot; stacks values, &quot;percent&quot; normalizes to 100%, &quot;side_by_side&quot; places bars next to each other.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_group_style? GroupStyle { get; set; }
        /// <summary>Map display height.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_height? Height { get; set; }
        /// <summary>Whether to hide groups with no data on the x-axis.</summary>
        public bool? HideEmptyGroups { get; set; }
        /// <summary>Whether to hide the shaded area under the line (line charts only).</summary>
        public bool? HideLineFillArea { get; set; }
        /// <summary>Whether to hide the title label (number charts only).</summary>
        public bool? HideTitle { get; set; }
        /// <summary>Whether the form is closed for submissions.</summary>
        public bool? IsFormClosed { get; set; }
        /// <summary>Legend display position. &quot;off&quot; hides the legend.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_legend_position? LegendPosition { get; set; }
        /// <summary>Property ID of the location property used to position items on the map.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapBy { get; set; }
#nullable restore
#else
        public string MapBy { get; set; }
#endif
        /// <summary>Map-by property name (convenience field).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MapByPropertyName { get; set; }
#nullable restore
#else
        public string MapByPropertyName { get; set; }
#endif
        /// <summary>Timeline zoom/preference state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.TimelinePreferenceResponse? Preference { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.TimelinePreferenceResponse Preference { get; set; }
#endif
        /// <summary>Columns/properties visible in the table view.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>? Properties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse> Properties { get; set; }
#endif
        /// <summary>Reference lines drawn on the chart. Null when no reference lines are configured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines? ReferenceLines { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines ReferenceLines { get; set; }
#endif
        /// <summary>The rows that make up the dashboard layout. Each row contains one or more widget modules.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.DashboardRowResponse>? Rows { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.DashboardRowResponse> Rows { get; set; }
#endif
        /// <summary>Whether to show data value labels on chart elements.</summary>
        public bool? ShowDataLabels { get; set; }
        /// <summary>Whether to show the table panel alongside the timeline.</summary>
        public bool? ShowTable { get; set; }
        /// <summary>Whether to show vertical lines between columns.</summary>
        public bool? ShowVerticalLines { get; set; }
        /// <summary>Whether to show weekend days.</summary>
        public bool? ShowWeekends { get; set; }
        /// <summary>Whether to use smooth curves (line charts only).</summary>
        public bool? SmoothLine { get; set; }
        /// <summary>Sort order for chart data.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_sort? Sort { get; set; }
        /// <summary>Stack-by grouping configuration for stacked/grouped bar charts (column/bar/line only). Null when not stacked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by? StackBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by StackBy { get; set; }
#endif
        /// <summary>Sub-grouping (vertical swimlanes within columns).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse? SubGroupBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse SubGroupBy { get; set; }
#endif
        /// <summary>Permission level granted to the submitter on the created page after form submission.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_submission_permissions? SubmissionPermissions { get; set; }
        /// <summary>Sub-item (subtask) display configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.SubtaskConfigResponse? Subtasks { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.SubtaskConfigResponse Subtasks { get; set; }
#endif
        /// <summary>Properties to display in the table panel (when show_table is true).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>? TableProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse> TableProperties { get; set; }
#endif
        /// <summary>The view configuration type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Aggregation configuration for number charts (single value display).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse Value { get; set; }
#endif
        /// <summary>Calendar view range.</summary>
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_view_range? ViewRange { get; set; }
        /// <summary>Whether to wrap cell content by default.</summary>
        public bool? WrapCells { get; set; }
        /// <summary>X-axis grouping configuration for column/bar/line/donut charts using grouped data. Null when using results (raw property values) mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis? XAxis { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis XAxis { get; set; }
#endif
        /// <summary>Property ID for the x-axis name values when using results (raw property values) mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XAxisPropertyId { get; set; }
#nullable restore
#else
        public string XAxisPropertyId { get; set; }
#endif
        /// <summary>Y-axis aggregation for column/bar/line/donut charts using grouped data. Null when using results mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis? YAxis { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis YAxis { get; set; }
#endif
        /// <summary>Custom maximum value for the y-axis. Null clears the override.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max? YAxisMax { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max YAxisMax { get; set; }
#endif
        /// <summary>Custom minimum value for the y-axis. Null clears the override.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min? YAxisMin { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min YAxisMin { get; set; }
#endif
        /// <summary>Property ID for the y-axis numeric values when using results (raw property values) mode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YAxisPropertyId { get; set; }
#nullable restore
#else
        public string YAxisPropertyId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse"/> and sets the default values.
        /// </summary>
        public ViewConfigResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "anonymous_submissions", n => { AnonymousSubmissions = n.GetBoolValue(); } },
                { "arrows_by", n => { ArrowsBy = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.TimelineArrowsByResponse>(global::Soenneker.Notion.OpenApiClient.Models.TimelineArrowsByResponse.CreateFromDiscriminatorValue); } },
                { "axis_labels", n => { AxisLabels = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_axis_labels>(); } },
                { "caption", n => { Caption = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption.CreateFromDiscriminatorValue); } },
                { "card_layout", n => { CardLayout = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_card_layout>(); } },
                { "chart_type", n => { ChartType = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_chart_type>(); } },
                { "color_by", n => { ColorBy = n.GetBoolValue(); } },
                { "color_by_value", n => { ColorByValue = n.GetBoolValue(); } },
                { "color_theme", n => { ColorTheme = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_color_theme>(); } },
                { "cover", n => { Cover = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.CoverConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.CoverConfigResponse.CreateFromDiscriminatorValue); } },
                { "cover_aspect", n => { CoverAspect = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_aspect>(); } },
                { "cover_size", n => { CoverSize = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_size>(); } },
                { "cumulative", n => { Cumulative = n.GetBoolValue(); } },
                { "date_property_id", n => { DatePropertyId = n.GetStringValue(); } },
                { "date_property_name", n => { DatePropertyName = n.GetStringValue(); } },
                { "donut_labels", n => { DonutLabels = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_donut_labels>(); } },
                { "end_date_property_id", n => { EndDatePropertyId = n.GetStringValue(); } },
                { "end_date_property_name", n => { EndDatePropertyName = n.GetStringValue(); } },
                { "frozen_column_index", n => { FrozenColumnIndex = n.GetIntValue(); } },
                { "grid_lines", n => { GridLines = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_grid_lines>(); } },
                { "group_by", n => { GroupBy = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse.CreateFromDiscriminatorValue); } },
                { "group_style", n => { GroupStyle = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_group_style>(); } },
                { "height", n => { Height = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_height>(); } },
                { "hide_empty_groups", n => { HideEmptyGroups = n.GetBoolValue(); } },
                { "hide_line_fill_area", n => { HideLineFillArea = n.GetBoolValue(); } },
                { "hide_title", n => { HideTitle = n.GetBoolValue(); } },
                { "is_form_closed", n => { IsFormClosed = n.GetBoolValue(); } },
                { "legend_position", n => { LegendPosition = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_legend_position>(); } },
                { "map_by", n => { MapBy = n.GetStringValue(); } },
                { "map_by_property_name", n => { MapByPropertyName = n.GetStringValue(); } },
                { "preference", n => { Preference = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.TimelinePreferenceResponse>(global::Soenneker.Notion.OpenApiClient.Models.TimelinePreferenceResponse.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reference_lines", n => { ReferenceLines = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines.CreateFromDiscriminatorValue); } },
                { "rows", n => { Rows = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.DashboardRowResponse>(global::Soenneker.Notion.OpenApiClient.Models.DashboardRowResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "show_data_labels", n => { ShowDataLabels = n.GetBoolValue(); } },
                { "show_table", n => { ShowTable = n.GetBoolValue(); } },
                { "show_vertical_lines", n => { ShowVerticalLines = n.GetBoolValue(); } },
                { "show_weekends", n => { ShowWeekends = n.GetBoolValue(); } },
                { "smooth_line", n => { SmoothLine = n.GetBoolValue(); } },
                { "sort", n => { Sort = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_sort>(); } },
                { "stack_by", n => { StackBy = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by.CreateFromDiscriminatorValue); } },
                { "sub_group_by", n => { SubGroupBy = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse.CreateFromDiscriminatorValue); } },
                { "submission_permissions", n => { SubmissionPermissions = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_submission_permissions>(); } },
                { "subtasks", n => { Subtasks = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.SubtaskConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.SubtaskConfigResponse.CreateFromDiscriminatorValue); } },
                { "table_properties", n => { TableProperties = n.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>(global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse>(global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse.CreateFromDiscriminatorValue); } },
                { "view_range", n => { ViewRange = n.GetEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_view_range>(); } },
                { "wrap_cells", n => { WrapCells = n.GetBoolValue(); } },
                { "x_axis", n => { XAxis = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis.CreateFromDiscriminatorValue); } },
                { "x_axis_property_id", n => { XAxisPropertyId = n.GetStringValue(); } },
                { "y_axis", n => { YAxis = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis.CreateFromDiscriminatorValue); } },
                { "y_axis_max", n => { YAxisMax = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max.CreateFromDiscriminatorValue); } },
                { "y_axis_min", n => { YAxisMin = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min>(global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min.CreateFromDiscriminatorValue); } },
                { "y_axis_property_id", n => { YAxisPropertyId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("anonymous_submissions", AnonymousSubmissions);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.TimelineArrowsByResponse>("arrows_by", ArrowsBy);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_axis_labels>("axis_labels", AxisLabels);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption>("caption", Caption);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_card_layout>("card_layout", CardLayout);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_chart_type>("chart_type", ChartType);
            writer.WriteBoolValue("color_by", ColorBy);
            writer.WriteBoolValue("color_by_value", ColorByValue);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_color_theme>("color_theme", ColorTheme);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.CoverConfigResponse>("cover", Cover);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_aspect>("cover_aspect", CoverAspect);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_cover_size>("cover_size", CoverSize);
            writer.WriteBoolValue("cumulative", Cumulative);
            writer.WriteStringValue("date_property_id", DatePropertyId);
            writer.WriteStringValue("date_property_name", DatePropertyName);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_donut_labels>("donut_labels", DonutLabels);
            writer.WriteStringValue("end_date_property_id", EndDatePropertyId);
            writer.WriteStringValue("end_date_property_name", EndDatePropertyName);
            writer.WriteIntValue("frozen_column_index", FrozenColumnIndex);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_grid_lines>("grid_lines", GridLines);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>("group_by", GroupBy);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_group_style>("group_style", GroupStyle);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_height>("height", Height);
            writer.WriteBoolValue("hide_empty_groups", HideEmptyGroups);
            writer.WriteBoolValue("hide_line_fill_area", HideLineFillArea);
            writer.WriteBoolValue("hide_title", HideTitle);
            writer.WriteBoolValue("is_form_closed", IsFormClosed);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_legend_position>("legend_position", LegendPosition);
            writer.WriteStringValue("map_by", MapBy);
            writer.WriteStringValue("map_by_property_name", MapByPropertyName);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.TimelinePreferenceResponse>("preference", Preference);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>("properties", Properties);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines>("reference_lines", ReferenceLines);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.DashboardRowResponse>("rows", Rows);
            writer.WriteBoolValue("show_data_labels", ShowDataLabels);
            writer.WriteBoolValue("show_table", ShowTable);
            writer.WriteBoolValue("show_vertical_lines", ShowVerticalLines);
            writer.WriteBoolValue("show_weekends", ShowWeekends);
            writer.WriteBoolValue("smooth_line", SmoothLine);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_sort>("sort", Sort);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by>("stack_by", StackBy);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>("sub_group_by", SubGroupBy);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_submission_permissions>("submission_permissions", SubmissionPermissions);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.SubtaskConfigResponse>("subtasks", Subtasks);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ViewPropertyConfigResponse>("table_properties", TableProperties);
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse>("value", Value);
            writer.WriteEnumValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_view_range>("view_range", ViewRange);
            writer.WriteBoolValue("wrap_cells", WrapCells);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis>("x_axis", XAxis);
            writer.WriteStringValue("x_axis_property_id", XAxisPropertyId);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis>("y_axis", YAxis);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max>("y_axis_max", YAxisMax);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min>("y_axis_min", YAxisMin);
            writer.WriteStringValue("y_axis_property_id", YAxisPropertyId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_caption : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1? ViewConfigResponseCaptionMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1 ViewConfigResponseCaptionMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_caption();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseCaptionMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1();
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ViewConfigResponseCaptionMember1 != null)
                {
                    return ViewConfigResponseCaptionMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ViewConfigResponseCaptionMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_captionMember1>(null, ViewConfigResponseCaptionMember1);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1"/>, List&lt;global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_reference_lines : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse>? ChartReferenceLineResponse { get; set; }
#nullable restore
#else
            public List<global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse> ChartReferenceLineResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1? ViewConfigResponseReferenceLinesMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1 ViewConfigResponseReferenceLinesMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_reference_lines();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseReferenceLinesMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1();
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse>(global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse> chartReferenceLineResponseValue)
                {
                    result.ChartReferenceLineResponse = chartReferenceLineResponseValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ViewConfigResponseReferenceLinesMember1 != null)
                {
                    return ViewConfigResponseReferenceLinesMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ViewConfigResponseReferenceLinesMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_reference_linesMember1>(null, ViewConfigResponseReferenceLinesMember1);
                }
                else if(ChartReferenceLineResponse != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Soenneker.Notion.OpenApiClient.Models.ChartReferenceLineResponse>(null, ChartReferenceLineResponse);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_stack_by : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse? GroupByConfigResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse GroupByConfigResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1? ViewConfigResponseStackByMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1 ViewConfigResponseStackByMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_stack_by();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GroupByConfigResponse = new global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseStackByMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GroupByConfigResponse != null)
                {
                    return GroupByConfigResponse.GetFieldDeserializers();
                }
                else if(ViewConfigResponseStackByMember1 != null)
                {
                    return ViewConfigResponseStackByMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GroupByConfigResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>(null, GroupByConfigResponse);
                }
                else if(ViewConfigResponseStackByMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_stack_byMember1>(null, ViewConfigResponseStackByMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_x_axis : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse? GroupByConfigResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse GroupByConfigResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1? ViewConfigResponseXAxisMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1 ViewConfigResponseXAxisMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_x_axis();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GroupByConfigResponse = new global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseXAxisMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GroupByConfigResponse != null)
                {
                    return GroupByConfigResponse.GetFieldDeserializers();
                }
                else if(ViewConfigResponseXAxisMember1 != null)
                {
                    return ViewConfigResponseXAxisMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GroupByConfigResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.GroupByConfigResponse>(null, GroupByConfigResponse);
                }
                else if(ViewConfigResponseXAxisMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_x_axisMember1>(null, ViewConfigResponseXAxisMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_y_axis : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse? ChartAggregationResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse ChartAggregationResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1? ViewConfigResponseYAxisMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1 ViewConfigResponseYAxisMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis();
                if("chartAggregationResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ChartAggregationResponse = new global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseYAxisMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChartAggregationResponse != null)
                {
                    return ChartAggregationResponse.GetFieldDeserializers();
                }
                else if(ViewConfigResponseYAxisMember1 != null)
                {
                    return ViewConfigResponseYAxisMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ChartAggregationResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ChartAggregationResponse>(null, ChartAggregationResponse);
                }
                else if(ViewConfigResponseYAxisMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axisMember1>(null, ViewConfigResponseYAxisMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_y_axis_max : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1? ViewConfigResponseYAxisMaxMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1 ViewConfigResponseYAxisMaxMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_max();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseYAxisMaxMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1();
                }
                else if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ViewConfigResponseYAxisMaxMember1 != null)
                {
                    return ViewConfigResponseYAxisMaxMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ViewConfigResponseYAxisMaxMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_maxMember1>(null, ViewConfigResponseYAxisMaxMember1);
                }
                else if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ViewConfigResponse_y_axis_min : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1? ViewConfigResponseYAxisMinMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1 ViewConfigResponseYAxisMinMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse.ViewConfigResponse_y_axis_min();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ViewConfigResponseYAxisMinMember1 = new global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1();
                }
                else if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ViewConfigResponseYAxisMinMember1 != null)
                {
                    return ViewConfigResponseYAxisMinMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ViewConfigResponseYAxisMinMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.Models.ViewConfigResponse_y_axis_minMember1>(null, ViewConfigResponseYAxisMinMember1);
                }
                else if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
            }
        }
    }
}
#pragma warning restore CS0618
