// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>The object type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ViewQueryResponse_object
    {
        [EnumMember(Value = "view_query")]
        #pragma warning disable CS1591
        ViewQuery,
        #pragma warning restore CS1591
    }
}
