// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Time display format (date properties only). &quot;12_hour&quot; = 12-hour clock with AM/PM, &quot;24_hour&quot; = 24-hour clock, &quot;hidden&quot; = hide time.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ViewPropertyConfigResponse_time_format
    {
        [EnumMember(Value = "12_hour")]
        #pragma warning disable CS1591
        OneTwo_hour,
        #pragma warning restore CS1591
        [EnumMember(Value = "24_hour")]
        #pragma warning disable CS1591
        TwoFour_hour,
        #pragma warning restore CS1591
        [EnumMember(Value = "hidden")]
        #pragma warning disable CS1591
        Hidden,
        #pragma warning restore CS1591
    }
}
