// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Card layout mode (list shows all properties, compact shows inline).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ViewConfigResponse_card_layout
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "compact")]
        #pragma warning disable CS1591
        Compact,
        #pragma warning restore CS1591
    }
}
