// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Notion.OpenApiClient.Models
{
    /// <summary>Permission level granted to the submitter on the created page after form submission.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ViewConfigResponse_submission_permissions
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_only")]
        #pragma warning disable CS1591
        Comment_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
        [EnumMember(Value = "read_and_write")]
        #pragma warning disable CS1591
        Read_and_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
    }
}
