// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarkdownPatchRequestBodyMember3 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Always `update_content`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Update specific content using search-and-replace operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3_update_content? UpdateContent { get; set; }
#nullable restore
#else
        public global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3_update_content UpdateContent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3"/> and sets the default values.
        /// </summary>
        public MarkdownPatchRequestBodyMember3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "type", n => { Type = n.GetStringValue(); } },
                { "update_content", n => { UpdateContent = n.GetObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3_update_content>(global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3_update_content.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownPatchRequestBodyMember3_update_content>("update_content", UpdateContent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
