// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Notion.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\pages\{pageId}\markdown
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MarkdownRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarkdownRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/pages/{pageId}/markdown{?include_transcript*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarkdownRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/pages/{pageId}/markdown{?include_transcript*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a page as markdown
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi406">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi409">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi503">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi504">When receiving a 504 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi529">When receiving a 529 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder.MarkdownRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder.MarkdownRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi404.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi406.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi409.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi503.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi504.CreateFromDiscriminatorValue },
                { "529", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi529.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse>(requestInfo, global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a page&apos;s content as markdown
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi403">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi406">When receiving a 406 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi409">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi500">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi503">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi504">When receiving a 504 status code</exception>
        /// <exception cref="global::Soenneker.Notion.OpenApiClient.Models.ErrorApi529">When receiving a 529 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse?> PatchAsync(global::Soenneker.Notion.OpenApiClient.Models.UpdatePageMarkdownRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse> PatchAsync(global::Soenneker.Notion.OpenApiClient.Models.UpdatePageMarkdownRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi401.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi403.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi404.CreateFromDiscriminatorValue },
                { "406", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi406.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi409.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi500.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi503.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi504.CreateFromDiscriminatorValue },
                { "529", global::Soenneker.Notion.OpenApiClient.Models.ErrorApi529.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse>(requestInfo, global::Soenneker.Notion.OpenApiClient.Models.PageMarkdownResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a page as markdown
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder.MarkdownRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder.MarkdownRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a page&apos;s content as markdown
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Notion.OpenApiClient.Models.UpdatePageMarkdownRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Notion.OpenApiClient.Models.UpdatePageMarkdownRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Notion.OpenApiClient.V1.Pages.Item.Markdown.MarkdownRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve a page as markdown
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MarkdownRequestBuilderGetQueryParameters 
        {
            [QueryParameter("include_transcript")]
            public bool? IncludeTranscript { get; set; }
        }
    }
}
#pragma warning restore CS0618
