// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Notion.OpenApiClient.V1.Ai.Plugins;
using Soenneker.Notion.OpenApiClient.V1.Ai.Skills;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Notion.OpenApiClient.V1.Ai
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\ai
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The plugins property</summary>
        public global::Soenneker.Notion.OpenApiClient.V1.Ai.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Soenneker.Notion.OpenApiClient.V1.Ai.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The skills property</summary>
        public global::Soenneker.Notion.OpenApiClient.V1.Ai.Skills.SkillsRequestBuilder Skills
        {
            get => new global::Soenneker.Notion.OpenApiClient.V1.Ai.Skills.SkillsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/ai", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Notion.OpenApiClient.V1.Ai.AiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/ai", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
